package hub

import (
	"net/http"
	"text/template"
)

// modulePath is the Go module the installer builds the agent from.
const modulePath = "github.com/mkmik/boxel"

type installerData struct {
	HubURL        string // registration URL the agent dials; empty = agent autodiscovers via reflection
	PublicURL     string // URL the installer was fetched from (edge address)
	Token         string // agent token, empty unless the request was authenticated
	TokenRequired bool   // token is the hub's only registration method
	Module        string
	ModuleVersion string
	Version       string
}

// handleInstaller emits the curl|bash installer script. The script itself is
// not secret; the agent registration token is embedded only when the request
// passes Config.InstallerAuth (i.e. it carried the hub's client credentials),
// so serving this endpoint unauthenticated never leaks the token.
func (h *Hub) handleInstaller(w http.ResponseWriter, r *http.Request) {
	data := installerData{
		HubURL:        h.cfg.AdvertiseURL,
		PublicURL:     requestBaseURL(r),
		TokenRequired: h.cfg.OwnerEmail == "",
		Module:        modulePath,
		ModuleVersion: "latest",
		Version:       h.cfg.Version,
	}
	// With identity-based registration (exe.dev), an unset advertise URL is
	// fine: the agent discovers the hub's peer integration via reflection.
	// With token-only registration there is no discovery, so fall back to the
	// URL this script was fetched from.
	if data.HubURL == "" && data.TokenRequired {
		data.HubURL = data.PublicURL
	}
	if h.cfg.InstallerAuth != nil && h.cfg.InstallerAuth(r) {
		data.Token = h.cfg.AgentToken
	}
	w.Header().Set("Content-Type", "text/x-shellscript; charset=utf-8")
	w.Header().Set("Cache-Control", "no-store")
	_ = installerTmpl.Execute(w, data)
}

// requestBaseURL reconstructs the base URL the client used, honoring the
// forwarding proxy's protocol header.
func requestBaseURL(r *http.Request) string {
	proto := "http"
	if r.TLS != nil {
		proto = "https"
	}
	if xf := r.Header.Get("X-Forwarded-Proto"); xf != "" {
		proto = xf
	}
	return proto + "://" + r.Host
}

var installerTmpl = template.Must(template.New("installer").Parse(`#!/usr/bin/env bash
# boxel-agent installer, generated by the boxel hub ({{.Version}}).
#
# Installs the pull-mode boxel agent on this VM:
#   - builds boxel-agent with 'go install'
#   - registers and starts a systemd unit (boxel-agent.service)
# The agent dials out to the hub and registers under this VM's short
# hostname; the VM then becomes reachable at {{.PublicURL}}/vm/<hostname>/
# (MCP endpoint: {{.PublicURL}}/vm/<hostname>/mcp) with no inbound port.
#
# Usage:
#   curl -fsSL {{.PublicURL}}{{"/install-agent"}} | sudo bash
#
# Overridable environment:
#   BOXEL_HUB_URL          hub URL the agent dials      {{if .HubURL}}(default: {{.HubURL}}){{else}}(default: autodiscovered via reflection.int.exe.xyz){{end}}
#   BOXEL_HUB_INTEGRATION  peer integration name to discover (default: boxel-hub)
#   BOXEL_AGENT_TOKEN      registration token           {{if .Token}}(embedded in this script){{else if .TokenRequired}}(REQUIRED: this copy was served unauthenticated){{else}}(not needed: the hub accepts exe.dev identity){{end}}
#   BOXEL_AGENT_NAME       handle to register under     (default: short hostname; overridden by the platform-verified VM name on exe.dev)
#   BOXEL_AGENT_TARGET     local URL to forward to      (default: http://127.0.0.1:8080)
set -euo pipefail

HUB_URL="${BOXEL_HUB_URL:-{{.HubURL}}}"
HUB_INTEGRATION="${BOXEL_HUB_INTEGRATION:-}"
AGENT_TOKEN="${BOXEL_AGENT_TOKEN:-{{.Token}}}"
AGENT_NAME="${BOXEL_AGENT_NAME:-$(hostname -s | tr '[:upper:]' '[:lower:]')}"
TARGET_URL="${BOXEL_AGENT_TARGET:-http://127.0.0.1:8080}"
MODULE="{{.Module}}/cmd/boxel-agent@{{.ModuleVersion}}"

{{if .TokenRequired -}}
if [ -z "$AGENT_TOKEN" ]; then
  echo "error: no registration token." >&2
  echo "This hub only accepts token-based registration, and it embeds the token only" >&2
  echo "when the installer request is authenticated (e.g. fetched with the hub's" >&2
  echo "bearer token). Otherwise pass it explicitly:" >&2
  echo "  curl -fsSL {{.PublicURL}}{{"/install-agent"}} | sudo BOXEL_AGENT_TOKEN=<token> bash" >&2
  exit 1
fi
{{end -}}
if [ "$(id -u)" -ne 0 ]; then
  echo "error: run as root (installs to /usr/local/bin and registers a systemd unit):" >&2
  echo "  curl -fsSL {{.PublicURL}}{{"/install-agent"}} | sudo bash" >&2
  exit 1
fi
command -v systemctl >/dev/null 2>&1 || { echo "error: systemd is required" >&2; exit 1; }
command -v go >/dev/null 2>&1 || { echo "error: Go toolchain not found (needed for 'go install'); install Go first" >&2; exit 1; }

echo "==> go install $MODULE"
GOBIN=/usr/local/bin go install "$MODULE"

# The heavy lifting (service user, /etc/boxel-agent/env, systemd unit, local
# token reuse, hub reachability report) lives in the binary itself, so a VM
# that cannot reach the hub yet can bootstrap the same way with just:
#   go install {{.Module}}/cmd/boxel-agent@{{.ModuleVersion}} && sudo boxel-agent setup
env \
  BOXEL_HUB_URL="$HUB_URL" \
  BOXEL_HUB_INTEGRATION="$HUB_INTEGRATION" \
  BOXEL_AGENT_TOKEN="$AGENT_TOKEN" \
  BOXEL_AGENT_NAME="$AGENT_NAME" \
  BOXEL_AGENT_TARGET="$TARGET_URL" \
  /usr/local/bin/boxel-agent setup

echo
echo "Once registered, this VM is reachable through the hub at:"
echo "  {{.PublicURL}}/vm/$AGENT_NAME/"
echo "MCP endpoint:"
echo "  {{.PublicURL}}/vm/$AGENT_NAME/mcp"
`))
