package hub

import (
	"net/http"
	"text/template"
)

// modulePath is the Go module the installer builds the agent from.
const modulePath = "github.com/mkmik/boxel"

type installerData struct {
	HubURL        string // registration URL the agent dials; empty = agent autodiscovers via reflection
	PublicURL     string // URL the installer was fetched from (edge address)
	Token         string // agent token, empty unless the request was authenticated
	TokenRequired bool   // token is the hub's only registration method
	Module        string
	ModuleVersion string
	Version       string
}

// handleInstaller emits the curl|bash installer script. The script itself is
// not secret; the agent registration token is embedded only when the request
// passes Config.InstallerAuth (i.e. it carried the hub's client credentials),
// so serving this endpoint unauthenticated never leaks the token.
func (h *Hub) handleInstaller(w http.ResponseWriter, r *http.Request) {
	data := installerData{
		HubURL:        h.cfg.AdvertiseURL,
		PublicURL:     requestBaseURL(r),
		TokenRequired: h.cfg.OwnerEmail == "",
		Module:        modulePath,
		ModuleVersion: "latest",
		Version:       h.cfg.Version,
	}
	// With identity-based registration (exe.dev), an unset advertise URL is
	// fine: the agent discovers the hub's peer integration via reflection.
	// With token-only registration there is no discovery, so fall back to the
	// URL this script was fetched from.
	if data.HubURL == "" && data.TokenRequired {
		data.HubURL = data.PublicURL
	}
	if h.cfg.InstallerAuth != nil && h.cfg.InstallerAuth(r) {
		data.Token = h.cfg.AgentToken
	}
	w.Header().Set("Content-Type", "text/x-shellscript; charset=utf-8")
	w.Header().Set("Cache-Control", "no-store")
	_ = installerTmpl.Execute(w, data)
}

// requestBaseURL reconstructs the base URL the client used, honoring the
// forwarding proxy's protocol header.
func requestBaseURL(r *http.Request) string {
	proto := "http"
	if r.TLS != nil {
		proto = "https"
	}
	if xf := r.Header.Get("X-Forwarded-Proto"); xf != "" {
		proto = xf
	}
	return proto + "://" + r.Host
}

var installerTmpl = template.Must(template.New("installer").Parse(`#!/usr/bin/env bash
# boxel agent installer, generated by the boxel hub ({{.Version}}).
#
# Installs boxel on this VM as a SINGLE pull-mode agent process:
#   - builds tunnel-mcp with 'go install'
#   - runs it as the VM's MAIN user (default: exedev, override with
#     BOXEL_AGENT_USER) in that user's natural home directory — no dedicated
#     service user is created
#   - registers and starts a systemd unit (boxel-agent.service) running
#     'tunnel-mcp --hub-connect': the process dials OUT to the hub and serves
#     its MCP in-process over the reverse channel — no local port, no
#     separate boxel-agent forwarder process. The unit carries no systemd
#     sandboxing and the agent defaults to bypassPermissions: the VM is the
#     sandbox
#   - enables a self-update timer (boxel-agent-update.timer) that polls for
#     newer releases every 5 minutes and installs them
# The VM then becomes reachable at {{.PublicURL}}/vm/<hostname>/
# (MCP endpoint: {{.PublicURL}}/vm/<hostname>/mcp) with no inbound port.
#
# Usage:
#   curl -fsSL {{.PublicURL}}{{"/install-agent"}} | sudo bash
#
# Overridable environment:
#   BOXEL_HUB_URL          hub URL the agent dials      {{if .HubURL}}(default: {{.HubURL}}){{else}}(default: autodiscovered via reflection.int.exe.xyz){{end}}
#   BOXEL_HUB_INTEGRATION  peer integration name to discover (default: boxel)
#   BOXEL_AGENT_TOKEN      registration token           {{if .Token}}(embedded in this script){{else if .TokenRequired}}(REQUIRED: this copy was served unauthenticated){{else}}(not needed: the hub accepts exe.dev identity){{end}}
#   BOXEL_AGENT_NAME       handle to register under     (default: short hostname; overridden by the platform-verified VM name on exe.dev)
#   BOXEL_AGENT_USER       user the agent runs as       (default: exedev — the VM's main user)
#   BOXEL_WORKSPACE        workspace jail root          (default: the agent user's home directory)
set -euo pipefail

HUB_URL="${BOXEL_HUB_URL:-{{.HubURL}}}"
HUB_INTEGRATION="${BOXEL_HUB_INTEGRATION:-}"
AGENT_TOKEN="${BOXEL_AGENT_TOKEN:-{{.Token}}}"
AGENT_NAME="${BOXEL_AGENT_NAME:-$(hostname -s | tr '[:upper:]' '[:lower:]')}"
SERVICE_USER="${BOXEL_AGENT_USER:-exedev}"
MODULE="{{.Module}}/cmd/tunnel-mcp@{{.ModuleVersion}}"

{{if .TokenRequired -}}
if [ -z "$AGENT_TOKEN" ]; then
  echo "error: no registration token." >&2
  echo "This hub only accepts token-based registration, and it embeds the token only" >&2
  echo "when the installer request is authenticated (e.g. fetched with the hub's" >&2
  echo "bearer token). Otherwise pass it explicitly:" >&2
  echo "  curl -fsSL {{.PublicURL}}{{"/install-agent"}} | sudo BOXEL_AGENT_TOKEN=<token> bash" >&2
  exit 1
fi
{{end -}}
if [ "$(id -u)" -ne 0 ]; then
  echo "error: run as root (installs to /usr/local/bin and registers a systemd unit):" >&2
  echo "  curl -fsSL {{.PublicURL}}{{"/install-agent"}} | sudo bash" >&2
  exit 1
fi
command -v systemctl >/dev/null 2>&1 || { echo "error: systemd is required" >&2; exit 1; }
command -v go >/dev/null 2>&1 || { echo "error: Go toolchain not found (needed for 'go install'); install Go first" >&2; exit 1; }
if ! id "$SERVICE_USER" >/dev/null 2>&1; then
  echo "error: user '$SERVICE_USER' not found. The agent runs as the VM's main user;" >&2
  echo "pass the right one explicitly:" >&2
  echo "  curl -fsSL {{.PublicURL}}{{"/install-agent"}} | sudo BOXEL_AGENT_USER=<user> bash" >&2
  exit 1
fi
SERVICE_GROUP="$(id -gn "$SERVICE_USER")"
USER_HOME="$(getent passwd "$SERVICE_USER" | cut -d: -f6)"
WORKSPACE="${BOXEL_WORKSPACE:-$USER_HOME}"

echo "==> go install $MODULE"
GOBIN=/usr/local/bin go install "$MODULE"

echo "==> agent runs as $SERVICE_USER (home: $USER_HOME, workspace: $WORKSPACE)"
if [ ! -d "$WORKSPACE" ]; then
  install -d -o "$SERVICE_USER" -g "$SERVICE_GROUP" "$WORKSPACE"
fi

echo "==> writing /etc/boxel-agent/env"
mkdir -p /etc/boxel-agent
{
  if [ -n "$HUB_URL" ]; then echo "BOXEL_HUB_URL=$HUB_URL"; fi
  if [ -n "$HUB_INTEGRATION" ]; then echo "BOXEL_HUB_INTEGRATION=$HUB_INTEGRATION"; fi
  if [ -n "$AGENT_TOKEN" ]; then echo "BOXEL_AGENT_TOKEN=$AGENT_TOKEN"; fi
  echo "BOXEL_AGENT_NAME=$AGENT_NAME"
} > /etc/boxel-agent/env
chown "root:$SERVICE_GROUP" /etc/boxel-agent /etc/boxel-agent/env
chmod 750 /etc/boxel-agent
chmod 640 /etc/boxel-agent/env

echo "==> installing boxel-agent.service (single tunnel-mcp --hub-connect process)"
cat > /etc/systemd/system/boxel-agent.service <<EOF
[Unit]
Description=boxel pull-mode agent (tunnel-mcp --hub-connect: serves MCP to the hub in-process)
After=network-online.target
Wants=network-online.target

[Service]
User=$SERVICE_USER
Group=$SERVICE_GROUP
EnvironmentFile=/etc/boxel-agent/env
Environment=HOME=$USER_HOME
WorkingDirectory=$WORKSPACE
ExecStart=/usr/local/bin/tunnel-mcp --hub-connect --workspace $WORKSPACE
Restart=always
RestartSec=2

# Deliberately NO systemd sandboxing (ProtectSystem & friends): the whole VM
# is the sandbox. The agent runs in bypassPermissions mode by default, and
# dev tools must be free to use the entire machine.

[Install]
WantedBy=multi-user.target
EOF

echo "==> installing self-update (boxel-agent-update.timer, every 5 minutes)"
cat > /usr/local/bin/boxel-agent-update <<'EOF'
#!/usr/bin/env bash
# boxel agent self-update: rebuild tunnel-mcp at its latest release and
# restart boxel-agent.service when the binary actually changes. Installed by
# the boxel hub installer; run as root by boxel-agent-update.timer.
set -euo pipefail
BIN=/usr/local/bin/tunnel-mcp
UNIT=boxel-agent.service
export HOME="${HOME:-/var/cache/boxel-agent-update}"
mkdir -p "$HOME"
GO=""
for p in go /usr/local/go/bin/go /usr/local/bin/go /usr/bin/go; do
  if command -v "$p" >/dev/null 2>&1; then GO="$(command -v "$p")"; break; fi
done
if [ -z "$GO" ]; then echo "go toolchain not found; not self-updating" >&2; exit 0; fi
# Derive the module from the installed binary (so forks self-update from
# their own module), and never clobber a source build (non-release version).
mod="$("$GO" version -m "$BIN" | awk '$1 == "mod" { print $2; exit }')"
ver="$("$GO" version -m "$BIN" | awk '$1 == "mod" { print $3; exit }')"
case "$ver" in
  v*) ;;
  *) echo "installed version $ver is not a released module version (source build?); not self-updating"; exit 0 ;;
esac
staging="$(mktemp -d /usr/local/bin/.tunnel-mcp-update-XXXXXX)"
trap 'rm -rf "$staging"' EXIT
GOBIN="$staging" "$GO" install "$mod/cmd/tunnel-mcp@latest"
if ! cmp -s "$staging/tunnel-mcp" "$BIN"; then
  mv "$staging/tunnel-mcp" "$BIN"
  # try-restart: pick up the new binary only if the service is running, so an
  # operator who stopped it deliberately doesn't get it back.
  systemctl try-restart "$UNIT"
  echo "updated $BIN"
fi
EOF
chmod 755 /usr/local/bin/boxel-agent-update

cat > /etc/systemd/system/boxel-agent-update.service <<EOF
[Unit]
Description=boxel agent self-update (installs the latest tunnel-mcp release)
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=/usr/local/bin/boxel-agent-update
Environment=HOME=/var/cache/boxel-agent-update
PrivateTmp=true
EOF

cat > /etc/systemd/system/boxel-agent-update.timer <<EOF
[Unit]
Description=poll for boxel agent updates every 5 minutes

[Timer]
OnBootSec=2min
OnUnitActiveSec=5min
RandomizedDelaySec=30s

[Install]
WantedBy=timers.target
EOF

echo "==> starting boxel-agent.service"
systemctl daemon-reload
systemctl enable boxel-agent.service
systemctl restart boxel-agent.service
systemctl enable --now boxel-agent-update.timer

echo
echo "boxel-agent.service is running a single tunnel-mcp process that dials the"
echo "hub and serves this VM's MCP in-process (no local port, no forwarder)."
if [ -z "$HUB_URL" ]; then
  echo
  echo "No hub URL was configured: the agent autodiscovers the hub's peer"
  echo "integration (name: ${HUB_INTEGRATION:-boxel}) via reflection and retries until it"
  echo "connects — the installation has SUCCEEDED even if the hub is not"
  echo "reachable yet; do not retry or roll back. If this VM is not in the"
  echo "fleet yet, the exe.dev account owner attaches it with:"
  echo "  ssh exe.dev integrations add http-proxy --name ${HUB_INTEGRATION:-boxel} \\"
  echo "    --target {{.PublicURL}}/ --peer --attach tag:boxel    # once per account"
  echo "  ssh exe.dev tag <this-vm> boxel"
fi
echo
echo "Verify with: journalctl -u boxel-agent.service -n 5   (look for \"registered with hub\")"
echo "Once registered, this VM is reachable through the hub at:"
echo "  {{.PublicURL}}/vm/$AGENT_NAME/"
echo "MCP endpoint:"
echo "  {{.PublicURL}}/vm/$AGENT_NAME/mcp"
`))
