package hub

import (
	"net/http"
	"text/template"
)

// modulePath is the Go module the installer builds the agent from.
const modulePath = "github.com/mkmik/boxel"

type installerData struct {
	HubURL        string // registration URL the agent dials (internal address)
	PublicURL     string // URL the installer was fetched from (edge address)
	Token         string // agent token, empty unless the request was authenticated
	Module        string
	ModuleVersion string
	Version       string
}

// handleInstaller emits the curl|bash installer script. The script itself is
// not secret; the agent registration token is embedded only when the request
// passes Config.InstallerAuth (i.e. it carried the hub's client credentials),
// so serving this endpoint unauthenticated never leaks the token.
func (h *Hub) handleInstaller(w http.ResponseWriter, r *http.Request) {
	data := installerData{
		HubURL:        h.cfg.AdvertiseURL,
		PublicURL:     requestBaseURL(r),
		Module:        modulePath,
		ModuleVersion: "latest",
		Version:       h.cfg.Version,
	}
	if data.HubURL == "" {
		data.HubURL = data.PublicURL
	}
	if h.cfg.InstallerAuth != nil && h.cfg.InstallerAuth(r) {
		data.Token = h.cfg.AgentToken
	}
	w.Header().Set("Content-Type", "text/x-shellscript; charset=utf-8")
	w.Header().Set("Cache-Control", "no-store")
	_ = installerTmpl.Execute(w, data)
}

// requestBaseURL reconstructs the base URL the client used, honoring the
// forwarding proxy's protocol header.
func requestBaseURL(r *http.Request) string {
	proto := "http"
	if r.TLS != nil {
		proto = "https"
	}
	if xf := r.Header.Get("X-Forwarded-Proto"); xf != "" {
		proto = xf
	}
	return proto + "://" + r.Host
}

var installerTmpl = template.Must(template.New("installer").Parse(`#!/usr/bin/env bash
# boxel-agent installer, generated by the boxel hub ({{.Version}}).
#
# Installs the pull-mode boxel agent on this VM:
#   - builds boxel-agent with 'go install'
#   - registers and starts a systemd unit (boxel-agent.service)
# The agent dials out to the hub and registers under this VM's short
# hostname; the VM then becomes reachable at {{.PublicURL}}/vm/<hostname>/
# (MCP endpoint: {{.PublicURL}}/vm/<hostname>/mcp) with no inbound port.
#
# Usage:
#   curl -fsSL {{.PublicURL}}{{"/install-agent"}} | sudo bash
#
# Overridable environment:
#   BOXEL_HUB_URL       hub URL the agent dials      (default: {{.HubURL}})
#   BOXEL_AGENT_TOKEN   registration token           {{if .Token}}(embedded in this script){{else}}(REQUIRED: this copy was served unauthenticated){{end}}
#   BOXEL_AGENT_NAME    handle to register under     (default: short hostname)
#   BOXEL_AGENT_TARGET  local URL to forward to      (default: http://127.0.0.1:8080)
set -euo pipefail

HUB_URL="${BOXEL_HUB_URL:-{{.HubURL}}}"
AGENT_TOKEN="${BOXEL_AGENT_TOKEN:-{{.Token}}}"
AGENT_NAME="${BOXEL_AGENT_NAME:-$(hostname -s | tr '[:upper:]' '[:lower:]')}"
TARGET_URL="${BOXEL_AGENT_TARGET:-http://127.0.0.1:8080}"
MODULE="{{.Module}}/cmd/boxel-agent@{{.ModuleVersion}}"

if [ -z "$AGENT_TOKEN" ]; then
  echo "error: no registration token." >&2
  echo "The hub embeds its agent token only when the installer request is authenticated" >&2
  echo "(e.g. fetched with the hub's bearer token). Otherwise pass it explicitly:" >&2
  echo "  curl -fsSL {{.PublicURL}}{{"/install-agent"}} | sudo BOXEL_AGENT_TOKEN=<token> bash" >&2
  exit 1
fi
if [ "$(id -u)" -ne 0 ]; then
  echo "error: run as root (installs to /usr/local/bin and registers a systemd unit):" >&2
  echo "  curl -fsSL {{.PublicURL}}{{"/install-agent"}} | sudo bash" >&2
  exit 1
fi
command -v systemctl >/dev/null 2>&1 || { echo "error: systemd is required" >&2; exit 1; }
command -v go >/dev/null 2>&1 || { echo "error: Go toolchain not found (needed for 'go install'); install Go first" >&2; exit 1; }

echo "==> go install $MODULE"
GOBIN=/usr/local/bin go install "$MODULE"

echo "==> configuring /etc/boxel-agent"
id boxel-agent >/dev/null 2>&1 || useradd --system --no-create-home --home-dir /nonexistent --shell /usr/sbin/nologin boxel-agent
install -d -m 750 -o root -g boxel-agent /etc/boxel-agent
ENV_FILE=/etc/boxel-agent/env
{
  printf 'BOXEL_HUB_URL=%s\n' "$HUB_URL"
  printf 'BOXEL_AGENT_TOKEN=%s\n' "$AGENT_TOKEN"
  printf 'BOXEL_AGENT_NAME=%s\n' "$AGENT_NAME"
  printf 'BOXEL_AGENT_TARGET=%s\n' "$TARGET_URL"
} > "$ENV_FILE"
# Reuse the local tunnel-mcp bearer token (if present) so forwarded requests
# authenticate to the boxel instance running on this VM.
if [ -r /etc/tunnel-mcp/token ]; then
  install -m 640 -o root -g boxel-agent /etc/tunnel-mcp/token /etc/boxel-agent/target-token
  printf 'BOXEL_AGENT_TARGET_TOKEN_FILE=/etc/boxel-agent/target-token\n' >> "$ENV_FILE"
fi
chown root:boxel-agent "$ENV_FILE"
chmod 640 "$ENV_FILE"

echo "==> installing systemd unit"
cat > /etc/systemd/system/boxel-agent.service <<'UNIT'
[Unit]
Description=boxel pull-mode agent (reverse tunnel to the boxel hub)
After=network-online.target
Wants=network-online.target

[Service]
User=boxel-agent
Group=boxel-agent
EnvironmentFile=/etc/boxel-agent/env
ExecStart=/usr/local/bin/boxel-agent
Restart=always
RestartSec=2
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
PrivateTmp=true
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
RestrictSUIDSGID=true
LockPersonality=true
MemoryDenyWriteExecute=true

[Install]
WantedBy=multi-user.target
UNIT

systemctl daemon-reload
systemctl enable --now boxel-agent
systemctl --no-pager --lines=3 status boxel-agent || true

echo
echo "boxel-agent installed; registering with $HUB_URL as \"$AGENT_NAME\"."
echo "Once connected, this VM is reachable through the hub at:"
echo "  {{.PublicURL}}/vm/$AGENT_NAME/"
echo "MCP endpoint:"
echo "  {{.PublicURL}}/vm/$AGENT_NAME/mcp"
`))
